### ISSUE TITLE
Generate unique URL for each Flyer

### ISSUE THREAD

**Issue by cjhaas** [vendi-advertising/vend-rotary-flyer#27]

**Comment by cjhaas** [comment]
Use `tempnam()` to create a unique file name per-request. Use MD5/SHA1 to hash as a token to return for pickup.

**Comment by Cdetviler** [comment]
Until v2, the priority here is just naming the PDF to something other than bill1234

**Comment by cjhaas** [comment]
This was resolved in the commits on Mar 7, 2018
