### ISSUE TITLE
have PDF generator check for admin approved status 

### ISSUE THREAD

**Issue by Cdetviler** [vendi-advertising/vend-rotary-flyer#6]

**Comment by Cdetviler** [comment]
The flow being:

1) flyer ad creator logs in
2) flyer ad creator works on ad which is then given "Draft" status
3) flyer ad creator moves on to finalize ad - the ad is given the "pending" status
4) admin logs in, checks payment (payment is independent of plugin), approves post by checking a boolean item on a separate ACF field group ( so that it does not show up on the front-end form)
5) advertisement prints successfully

**Comment by Cdetviler** [comment]
This creates the question: how do we handle who gets one of the 9 slots in each ad? If someone submits an entry but they do not pay right away, or the admin does not get to approving their ad right away, are they taking up one of the 9 ad slots available for that week? Or is it only paid and approved entries that take up a slot?

**Comment by cjhaas** [comment]
Let’s ask Kathy. My default gut response is to just put an asterisk on all entries that “not all submissions will be taken for the given date” and let the editor solve conflicts.  Maybe (and only a maybe) users could check a box that this entry “is a hard deadline” to voice their opinion to the editor that their ad should win conflict resolution all things being equal.

**Comment by cjhaas** [comment]
Also, (and also  just a maybe), content creators create ads and the editor’s responsibility is to turn them into “ads sheets”. We can provide defaults for the editor (last N expected ads which is probably good for 99% of cases) but makes _them_ bless it through the system.

**Comment by Cdetviler** [comment]
This should be clarified with Kathy on Monday. I am kind of going at it with two different schools of thought, and I think I confused people last week when more than 9 ads showed up in the admin preview.

**Comment by Cdetviler** [comment]
It's been decided to have posts be automatically published until an admin decides otherwise
